# Generated by Django 5.1.7 on 2025-08-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut de la proposition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_for_trade', to='items.item', verbose_name='Objet proposé')),
                ('item_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_for_trade', to='items.item', verbose_name='Objet demandé')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_made', to=settings.AUTH_USER_MODEL, verbose_name='Proposé par')),
            ],
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('trade_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trade.tradeoffer', verbose_name='Proposition de troc')),
            ],
        ),
    ]
