# Generated by Django 5.2.1 on 2025-08-04 12:46

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to=items.models.item_photo_path, verbose_name="Photo de l'objet"),
        ),
    ]
